<HTML>
<HEAD>
<meta charset="UTF-8">
<title>assertk.catch - assertk</title>
<link rel="stylesheet" href="../../style.css">
</HEAD>
<BODY>
<a href="../index.html">assertk</a>&nbsp;/&nbsp;<a href="index.html">assertk</a>&nbsp;/&nbsp;<a href="./catch.html">catch</a><br/>
<br/>
<h1>catch</h1>
<a name="assertk$catch(kotlin.Function0((kotlin.Unit)))"></a>
(common, iosArm64, iosX64, js, jvm, linux, macos) <code><span class="keyword">inline</span> <span class="keyword">fun </span><s><span class="identifier">catch</span></s><span class="symbol">(</span><span class="identifier" id="assertk$catch(kotlin.Function0((kotlin.Unit)))/f">f</span><span class="symbol">:</span>&nbsp;<span class="symbol">(</span><span class="symbol">)</span>&nbsp;<span class="symbol">-&gt;</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/index.html"><span class="identifier">Unit</span></a><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">?</span></code><br/>
<strong>Deprecated:</strong> Use assertThat { }.isFailure() instead<br/>
<br/>
<p>Catches any exceptions thrown in the given lambda and returns it. This is an easy way to assert on expected thrown
exceptions.</p>
<pre><code>val exception = catch { throw Exception("error") }
assertThat(exception).isNotNull().hasMessage("error")
</code></pre>
</BODY>
</HTML>
